In [62]:
docs = [
    'go india',
    'india india',
    'hip hip hurray',
    'jeetega bhai jeetega india jeetega',
    'bharat mata ki jai',
    'kohli kohli',
    'sachin sachin',
    'dhoni dhonni',
    'modi ji ke jai',
    'inquilab zindabad'
]

In [63]:
import tensorflow
from tensorflow.keras.preprocessing.text import Tokenizer

In [64]:
tokenizer = Tokenizer()

In [65]:
tokenizer.fit_on_texts(docs)

In [66]:
len(tokenizer.word_index)

19

In [67]:
sequences = tokenizer.texts_to_sequences(docs)
sequences

[[7, 1],
 [1, 1],
 [3, 3, 8],
 [2, 9, 2, 1, 2],
 [10, 11, 12, 4],
 [5, 5],
 [6, 6],
 [13, 14],
 [15, 16, 17, 4],
 [18, 19]]

In [68]:
vocab_size = len(tokenizer.word_index) + 1

In [69]:
from tensorflow.keras.utils import pad_sequences

In [70]:
sequences = pad_sequences(sequences,padding='post')

In [71]:
sequences

array([[ 7,  1,  0,  0,  0],
       [ 1,  1,  0,  0,  0],
       [ 3,  3,  8,  0,  0],
       [ 2,  9,  2,  1,  2],
       [10, 11, 12,  4,  0],
       [ 5,  5,  0,  0,  0],
       [ 6,  6,  0,  0,  0],
       [13, 14,  0,  0,  0],
       [15, 16, 17,  4,  0],
       [18, 19,  0,  0,  0]])

In [72]:
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Embedding

In [73]:
model = Sequential()

model.add(Embedding(input_dim=vocab_size,output_dim=2,input_length=5))

In [74]:
model.summary()

Model: "sequential_3"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_3 (Embedding)     (None, 5, 2)              40        
                                                                 
Total params: 40
Trainable params: 40
Non-trainable params: 0
_________________________________________________________________


In [75]:
import numpy as np
print(np.max(sequence))

19


In [76]:
model.compile('adam','accuracy')

In [79]:
pred = model.predict(sequences)
print(pred)

1/1 [==============================] - 0s 20ms/step
[[[-0.02462914  0.01691904]
  [-0.01528645  0.01022894]
  [ 0.0029561   0.01120331]
  [ 0.0029561   0.01120331]
  [ 0.0029561   0.01120331]]

 [[-0.01528645  0.01022894]
  [-0.01528645  0.01022894]
  [ 0.0029561   0.01120331]
  [ 0.0029561   0.01120331]
  [ 0.0029561   0.01120331]]

 [[-0.00213504  0.02789671]
  [-0.00213504  0.02789671]
  [-0.00323379 -0.01563803]
  [ 0.0029561   0.01120331]
  [ 0.0029561   0.01120331]]

 [[-0.01022677  0.04995061]
  [-0.02589582  0.04367436]
  [-0.01022677  0.04995061]
  [-0.01528645  0.01022894]
  [-0.01022677  0.04995061]]

 [[ 0.0377194  -0.04642634]
  [ 0.04295499 -0.02392118]
  [-0.03267197  0.02160374]
  [ 0.01591566  0.00744007]
  [ 0.0029561   0.01120331]]

 [[-0.03620937 -0.00032731]
  [-0.03620937 -0.00032731]
  [ 0.0029561   0.01120331]
  [ 0.0029561   0.01120331]
  [ 0.0029561   0.01120331]]

 [[-0.02414072 -0.03772705]
  [-0.02414072 -0.03772705]
  [ 0.0029561   0.01120331]
  [ 0.002956