In [31]:
import numpy as np
import pandas as pd

In [32]:
df = pd.DataFrame([[8,8,4],[7,9,5],[6,10,6],[5,12,7]],columns=['cgpa','profile_score','lpa'])

In [33]:
df.head()

,cgpa,profile_score,lpa
0,8,8,4
1,7,9,5
2,6,10,6
3,5,12,7


In [34]:
# Here we take W = 0.1 & b = 0
# This function initializes weights and bias

In [35]:
def initialize_parameters(layer_dims):
    
    np.random.seed(3)
    parameters = {}
    # No of layers
    L = len(layer_dims)
    
    # loop to calculate number of weights and bias
    for l in range(1,L):
        parameters['W'+str(l)] = np.ones((layer_dims[l-1],layer_dims[l]))*0.1
        parameters['b'+str(l)] = np.zeros((layer_dims[l],1))
        
    return parameters

In [36]:
initialize_parameters([2,2,1])

{'W1': array([[0.1, 0.1],
        [0.1, 0.1]]),
 'b1': array([[0.],
        [0.]]),
 'W2': array([[0.1],
        [0.1]]),
 'b2': array([[0.]])}

In [37]:
# Using formula z = w.Tx+b
# w = weights
# x = previous nodes value
# b = bias
# below A_prev = x

In [38]:
def linear_forward(A_prev ,W ,b):
    z = np.dot(W.T,A_prev) + b
    
    return z

In [50]:
# Forward Propogation
def L_layer_forward(x,parameters):
    A = x
    L = len(parameters) // 2  # Number of layers in neural network
    
    for l in range(1,L+1):
        A_prev = A
        W1 = parameters['W'+str(l)]
        b1 = parameters['b'+str(l)]
        print("A"+str(l-1)+": ",A_prev)
        print("W"+str(l)+": ",W1)
        print("b"+str(l)+": ",b1)
        print("--"*20)
        
        A = linear_forward(A_prev,W1,b1)
        print("A"+str(l)+": ",A)
        print("--"*20)
        
    return A,A_prev
    

In [53]:
# The above code is for prediction on data
# lets take an exapmle by taking first student data
# Step 1 : Select 1 row(random)
x = df[['cgpa','profile_score']].values[0].reshape(2,1)
y = df[['lpa']].values[0][0]
x

array([[8],
       [8]], dtype=int64)

In [60]:
# Parameters initialize - same as we provide above
parameters = initialize_parameters([2,2,1])

# Step 2 : Predict using forward propogation
y_hat,A1 = L_layer_forward(x,parameters)


A0:  [[8]
 [8]]
W1:  [[0.1 0.1]
 [0.1 0.1]]
b1:  [[0.]
 [0.]]
----------------------------------------
A1:  [[1.6]
 [1.6]]
----------------------------------------
A1:  [[1.6]
 [1.6]]
W2:  [[0.1]
 [0.1]]
b2:  [[0.]]
----------------------------------------
A2:  [[0.32]]
----------------------------------------


In [66]:
y_hat

array([[0.32]])

In [67]:
A1

array([[1.6],
       [1.6]])

In [65]:
# Loss for first student - (y-y_hat)^2
# Step 3 : Calculate loss
loss = (y-y_hat[0][0])**2
loss

13.542399999999997

In [58]:
# Step 4: Update weights and bias using gd

In [59]:
def update_parameters(parameters,y,y_hat,A1,x):
    # param_new = param_old - lr * gradient
    parameters['W2'][0][0] = parameters['W2'][0][0] + (0.001 * 2 * (y-y_hat) * A1[0][0])
    parameters['W2'][1][0] = parameters['W2'][1][0] + (0.001 * 2 * (y-y_hat) * A1[1][0])
    parameters['b2'][0][0] = parameters['b2'][0][0] + (0.001 * 2 * (y-y_hat))
    
    parameters['W1'][0][0] = parameters['W1'][0][0] + (0.001 * 2 * (y-y_hat) * parameters['W2'][0][0] * x[0][0])
    parameters['W1'][0][1] = parameters['W1'][0][1] + (0.001 * 2 * (y-y_hat) * parameters['W2'][0][0] * x[1][0])
    parameters['b1'][0][0] = parameters['b1'][0][0] + (0.001 * 2 * (y-y_hat) * parameters['W2'][0][0])
    
    parameters['W1'][1][0] = parameters['W1'][1][0] + (0.001 * 2 * (y-y_hat) * parameters['W2'][1][0] * x[0][0])
    parameters['W1'][1][1] = parameters['W1'][1][1] + (0.001 * 2 * (y-y_hat) * parameters['W2'][1][0] * x[1][0])
    parameters['b1'][1][0] = parameters['b1'][1][0] + (0.001 * 2 * (y-y_hat) * parameters['W2'][1][0])
    
    
    

In [68]:
update_parameters(parameters,y,y_hat[0][0],A1,x)

In [69]:
# updated parameters
parameters

{'W1': array([[0.10658137, 0.10658137],
        [0.10658137, 0.10658137]]),
 'b1': array([[0.00082267],
        [0.00082267]]),
 'W2': array([[0.111776],
        [0.111776]]),
 'b2': array([[0.00736]])}

In [ ]:
## For student 2

In [87]:
# 1. select x and y
x = df[['cgpa','profile_score']].values[1].reshape(2,1)
y = df['lpa'].values[0]
x

array([[7],
       [9]], dtype=int64)

In [97]:
# 2.predict 
parameters = initialize_parameters([2,2,1])
y_hat,A1 = L_layer_forward(x,parameters)

A0:  [[7]
 [9]]
W1:  [[0.1 0.1]
 [0.1 0.1]]
b1:  [[0.]
 [0.]]
----------------------------------------
A1:  [[1.6]
 [1.6]]
----------------------------------------
A1:  [[1.6]
 [1.6]]
W2:  [[0.1]
 [0.1]]
b2:  [[0.]]
----------------------------------------
A2:  [[0.32]]
----------------------------------------


In [101]:
# 3. calulate loss
y_hat = y_hat[0][0]

In [103]:
loss = (y-y_hat)**2
loss

13.542399999999997

In [104]:
# 4. update weights and bias
update_parameters(parameters,y,y_hat,A1,x)

In [105]:
# updated weights and bias
parameters

{'W1': array([[0.1057587 , 0.10740404],
        [0.1057587 , 0.10740404]]),
 'b1': array([[0.00082267],
        [0.00082267]]),
 'W2': array([[0.111776],
        [0.111776]]),
 'b2': array([[0.00736]])}

In [107]:
# Forward Propogation
def L_layer_forward(x,parameters):
    A = x
    L = len(parameters) // 2  # Number of layers in neural network
    
    for l in range(1,L+1):
        A_prev = A
        W1 = parameters['W'+str(l)]
        b1 = parameters['b'+str(l)]
        # print("A"+str(l-1)+": ",A_prev)
        # print("W"+str(l)+": ",W1)
        # print("b"+str(l)+": ",b1)
        # print("--"*20)
        
        A = linear_forward(A_prev,W1,b1)
        # print("A"+str(l)+": ",A)
        # print("--"*20)
        
    return A,A_prev

In [113]:
# Epoch implementation

parameters = initialize_parameters([2,2,1])
epochs = 7

for i in range(epochs):
    Loss = []
    
    for j in range(df.shape[0]):
        
        x = df[['cgpa','profile_score']].values[j].reshape(2,1)
        y = df[['lpa']].values[j][0]
        
        # parameters initialization
        
        y_hat , A1 = L_layer_forward(x,parameters)
        y_hat = y_hat[0][0]
        
        # update parameters
        update_parameters(parameters,y,y_hat,A1,x)
        
        Loss.append((y-y_hat)**2)
    
    print('Epoch -',i+1,'Loss - ',np.array(Loss).mean())
    
parameters

Epoch - 1 Loss -  26.28249792398698
Epoch - 2 Loss -  19.438253848220803
Epoch - 3 Loss -  10.139874435827522
Epoch - 4 Loss -  3.385561305106485
Epoch - 5 Loss -  1.3198454128484565
Epoch - 6 Loss -  1.152495614758268
Epoch - 7 Loss -  1.2167000755723476


{'W1': array([[0.27199786, 0.41893516],
        [0.28619297, 0.44932568]]),
 'b1': array([[0.02983884],
        [0.03252541]]),
 'W2': array([[0.43580768],
        [0.5180243 ]]),
 'b2': array([[0.12049599]])}

In [114]:
# Now lets use keras to make the same things

In [115]:
import tensorflow
from tensorflow import keras
from keras import Sequential
from keras.layers import Dense

In [116]:
model = Sequential()

model.add(Dense(2,activation='linear',input_dim=2))
model.add(Dense(1,activation='linear'))

In [120]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 2)                 6         
                                                                 
 dense_1 (Dense)             (None, 1)                 3         
                                                                 
Total params: 9
Trainable params: 9
Non-trainable params: 0
_________________________________________________________________


In [121]:
model.get_weights()

[array([[-0.29902518, -1.021511  ],
        [-0.64196104,  0.14710677]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[-0.96256185],
        [-1.0402645 ]], dtype=float32),
 array([0.], dtype=float32)]

In [ ]:
# Keras initialize weights and bias randomly
# to make it similar to what we did above we'll create new weights and bias 

In [122]:
new_weights = [np.array([[0.1 ,0.1],
                        [0.1,0.1]],dtype=np.float32),
                np.array([0. , 0.],dtype=np.float32),
                np.array([[0.1],
                          [0.1]],dtype=np.float32),
                np.array([0.],dtype=np.float32)
               ]

In [123]:
model.set_weights(new_weights)

In [126]:
model.get_weights()

[array([[0.1, 0.1],
        [0.1, 0.1]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[0.1],
        [0.1]], dtype=float32),
 array([0.], dtype=float32)]

In [127]:
optimizer = keras.optimizers.Adam(learning_rate=0.001)
model.compile(loss='mean_squared_error',optimizer=optimizer)

In [129]:
model.fit(df.iloc[:,0:-1].values,df['lpa'].values,epochs=75,verbose=1,batch_size=1)

Epoch 1/75
4/4 [==============================] - 0s 3ms/step - loss: 1.4472
Epoch 2/75
4/4 [==============================] - 0s 4ms/step - loss: 1.4079
Epoch 3/75
4/4 [==============================] - 0s 5ms/step - loss: 1.3645
Epoch 4/75
4/4 [==============================] - 0s 4ms/step - loss: 1.3172
Epoch 5/75
4/4 [==============================] - 0s 5ms/step - loss: 1.2888
Epoch 6/75
4/4 [==============================] - 0s 4ms/step - loss: 1.2543
Epoch 7/75
4/4 [==============================] - 0s 4ms/step - loss: 1.2342
Epoch 8/75
4/4 [==============================] - 0s 6ms/step - loss: 1.1931
Epoch 9/75
4/4 [==============================] - 0s 3ms/step - loss: 1.1824
Epoch 10/75
4/4 [==============================] - 0s 6ms/step - loss: 1.1627
Epoch 11/75
4/4 [==============================] - 0s 4ms/step - loss: 1.1489
Epoch 12/75
4/4 [==============================] - 0s 6ms/step - loss: 1.1322
Epoch 13/75
4/4 [==============================] - 0s 4ms/step - loss: 1.