In [18]:
import numpy as np
import pandas as pd

In [19]:
df = pd.DataFrame([[8,8,1],[7,9,1],[6,10,0],[5,12,0]],columns=['cgpa','profile_score','placed'])

In [20]:
df.head()

,cgpa,profile_score,placed
0,8,8,1
1,7,9,1
2,6,10,0
3,5,12,0


In [22]:
def initialize_parameters(layer_dims):
    
    np.random.seed(3)
    parameters = {}
    # No of layers
    L = len(layer_dims)
    
    # loop to calculate number of weights and bias
    for l in range(1,L):
        parameters['W'+str(l)] = np.ones((layer_dims[l-1],layer_dims[l]))*0.1
        parameters['b'+str(l)] = np.zeros((layer_dims[l],1))
        
    return parameters

In [23]:
initialize_parameters([2,2,1])

{'W1': array([[0.1, 0.1],
        [0.1, 0.1]]),
 'b1': array([[0.],
        [0.]]),
 'W2': array([[0.1],
        [0.1]]),
 'b2': array([[0.]])}

In [ ]:
# utility function
# As activation funtion is sigmoid now
def sigmoid(z):
    A = 1/(1+np.exp(-z))
    
    
    return A

In [ ]:
def linear_forward(A_prev ,W ,b):
    z = np.dot(W.T,A_prev) + b
    
    # we'll pass output to sigmoid
    A = sigmoid(z)
    
    return A

In [27]:
# Forward Propogation
def L_layer_forward(x,parameters):
    A = x
    L = len(parameters) // 2  # Number of layers in neural network
    
    for l in range(1,L+1):
        A_prev = A
        W1 = parameters['W'+str(l)]
        b1 = parameters['b'+str(l)]
        print("A"+str(l-1)+": ",A_prev)
        print("W"+str(l)+": ",W1)
        print("b"+str(l)+": ",b1)
        print("--"*20)
        
        A = linear_forward(A_prev,W1,b1)
        print("A"+str(l)+": ",A)
        print("--"*20)
        
    return A,A_prev
    

In [46]:
def update_parameters(parameters,y,y_hat,A1,x):
    # param_new = param_old - lr * gradient
    parameters['W2'][0][0] = parameters['W2'][0][0] + (0.001 * (y-y_hat) * A1[0][0])
    parameters['W2'][1][0] = parameters['W2'][1][0] + (0.001 * (y-y_hat) * A1[1][0])
    parameters['b2'][0][0] = parameters['b2'][0][0] + (0.001 * (y-y_hat))
    
    parameters['W1'][0][0] = parameters['W1'][0][0] + (0.001 * (y-y_hat) * parameters['W2'][0][0] * A1[0][0] * (1-A1[0][0]) * x[0][0])  
    parameters['W1'][0][1] = parameters['W1'][0][1] + (0.001 * (y-y_hat) * parameters['W2'][0][0] * A1[0][0] * (1-A1[0][0]) * x[1][0])  
    parameters['b1'][0][0] = parameters['b1'][0][0] + (0.001 * (y-y_hat) * parameters['W2'][0][0] * A1[0][0] * (1-A1[0][0]))  
    
    parameters['W1'][1][0] = parameters['W1'][1][0] + (0.001 * (y-y_hat) * parameters['W2'][1][0] * A1[1][0] * (1-A1[1][0]) * x[0][0])  
    parameters['W1'][1][1] = parameters['W1'][1][1] + (0.001 * (y-y_hat) * parameters['W2'][1][0] * A1[1][0] * (1-A1[1][0]) * x[1][0])  
    parameters['b1'][1][0] = parameters['b1'][1][0] + (0.001 * (y-y_hat) * parameters['W2'][1][0] * A1[1][0] * (1-A1[1][0]))  
    
    
    

In [48]:
x = df[['cgpa','profile_score']].values[0].reshape(2,1)
y = df[['placed']].values[0][0]
x

array([[8],
       [8]], dtype=int64)

In [49]:
# Parameters initialize - same as we provide above
parameters = initialize_parameters([2,2,1])

# Step 2 : Predict using forward propogation
y_hat,A1 = L_layer_forward(x,parameters)
y_hat = y_hat[0][0]


update_parameters(parameters,y,y_hat,A1,x)

A0:  [[8]
 [8]]
W1:  [[0.1 0.1]
 [0.1 0.1]]
b1:  [[0.]
 [0.]]
----------------------------------------
A1:  [[0.83201839]
 [0.83201839]]
----------------------------------------
A1:  [[0.83201839]
 [0.83201839]]
W2:  [[0.1]
 [0.1]]
b2:  [[0.]]
----------------------------------------
A2:  [[0.54150519]]
----------------------------------------


In [50]:
# updated parameters
parameters

{'W1': array([[0.10005146, 0.10005146],
        [0.10005146, 0.10005146]]),
 'b1': array([[6.43254269e-06],
        [6.43254269e-06]]),
 'W2': array([[0.10038148],
        [0.10038148]]),
 'b2': array([[0.00045849]])}

In [ ]:
# For next student

In [52]:
# 1. select x and y
x = df[['cgpa','profile_score']].values[1].reshape(2,1)
y = df['placed'].values[0]
x

array([[7],
       [9]], dtype=int64)

In [53]:
# 2.predict 
parameters = initialize_parameters([2,2,1])
y_hat,A1 = L_layer_forward(x,parameters)

A0:  [[7]
 [9]]
W1:  [[0.1 0.1]
 [0.1 0.1]]
b1:  [[0.]
 [0.]]
----------------------------------------
A1:  [[0.83201839]
 [0.83201839]]
----------------------------------------
A1:  [[0.83201839]
 [0.83201839]]
W2:  [[0.1]
 [0.1]]
b2:  [[0.]]
----------------------------------------
A2:  [[0.54150519]]
----------------------------------------


In [54]:
# 3. calulate loss
y_hat = y_hat[0][0]

In [55]:
# 4. update weights and bias
update_parameters(parameters,y,y_hat,A1,x)

In [56]:
# updated weights and bias
parameters

{'W1': array([[0.10004503, 0.10005789],
        [0.10004503, 0.10005789]]),
 'b1': array([[6.43254269e-06],
        [6.43254269e-06]]),
 'W2': array([[0.10038148],
        [0.10038148]]),
 'b2': array([[0.00045849]])}

In [57]:
# Forward Propogation
def L_layer_forward(x,parameters):
    A = x
    L = len(parameters) // 2  # Number of layers in neural network
    
    for l in range(1,L+1):
        A_prev = A
        W1 = parameters['W'+str(l)]
        b1 = parameters['b'+str(l)]
        # print("A"+str(l-1)+": ",A_prev)
        # print("W"+str(l)+": ",W1)
        # print("b"+str(l)+": ",b1)
        # print("--"*20)
        
        A = linear_forward(A_prev,W1,b1)
        # print("A"+str(l)+": ",A)
        # print("--"*20)
        
    return A,A_prev

In [58]:
# Epoch implementation

parameters = initialize_parameters([2,2,1])
epochs = 7

for i in range(epochs):
    Loss = []
    
    for j in range(df.shape[0]):
        
        x = df[['cgpa','profile_score']].values[j].reshape(2,1)
        y = df[['placed']].values[j][0]
        
        # parameters initialization
        
        y_hat , A1 = L_layer_forward(x,parameters)
        y_hat = y_hat[0][0]
        
        # update parameters
        update_parameters(parameters,y,y_hat,A1,x)
        
        Loss.append((y-y_hat)**2)
    
    print('Epoch -',i+1,'Loss - ',np.array(Loss).mean())
    
parameters

Epoch - 1 Loss -  0.25205307757549694
Epoch - 2 Loss -  0.25204413772664624
Epoch - 3 Loss -  0.2520352415710494
Epoch - 4 Loss -  0.2520263888922104
Epoch - 5 Loss -  0.2520175794747218
Epoch - 6 Loss -  0.252008813104259
Epoch - 7 Loss -  0.25200008956757514


{'W1': array([[0.10011023, 0.09964424],
        [0.1001104 , 0.0996433 ]]),
 'b1': array([[-1.22696541e-05],
        [-1.23098980e-05]]),
 'W2': array([[0.09897798],
        [0.09897852]]),
 'b2': array([[-0.00116552]])}

In [114]:
# Now lets use keras to make the same things

In [59]:
import tensorflow
from tensorflow import keras
from keras import Sequential
from keras.layers import Dense

In [60]:
model = Sequential()

model.add(Dense(2,activation='linear',input_dim=2))
model.add(Dense(1,activation='linear'))

In [61]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 2)                 6         
                                                                 
 dense_1 (Dense)             (None, 1)                 3         
                                                                 
Total params: 9
Trainable params: 9
Non-trainable params: 0
_________________________________________________________________


In [62]:
model.get_weights()

[array([[ 0.13233292, -1.1282263 ],
        [ 0.8771485 ,  0.49666905]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[-0.8590812],
        [-1.0694517]], dtype=float32),
 array([0.], dtype=float32)]

In [ ]:
# Keras initialize weights and bias randomly
# to make it similar to what we did above we'll create new weights and bias 

In [63]:
new_weights = [np.array([[0.1 ,0.1],
                        [0.1,0.1]],dtype=np.float32),
                np.array([0. , 0.],dtype=np.float32),
                np.array([[0.1],
                          [0.1]],dtype=np.float32),
                np.array([0.],dtype=np.float32)
               ]

In [64]:
model.set_weights(new_weights)

In [65]:
model.get_weights()

[array([[0.1, 0.1],
        [0.1, 0.1]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[0.1],
        [0.1]], dtype=float32),
 array([0.], dtype=float32)]

In [70]:
optimizer = keras.optimizers.Adam(learning_rate=0.001)
model.compile(loss='binary_crossentropy',optimizer=optimizer)

In [71]:
model.fit(df.iloc[:,0:-1].values,df['placed'].values,epochs=75,verbose=1,batch_size=1)

Epoch 1/75
4/4 [==============================] - 3s 3ms/step - loss: 0.7778
Epoch 2/75
4/4 [==============================] - 0s 3ms/step - loss: 0.7763
Epoch 3/75
4/4 [==============================] - 0s 3ms/step - loss: 0.7564
Epoch 4/75
4/4 [==============================] - 0s 4ms/step - loss: 0.7586
Epoch 5/75
4/4 [==============================] - 0s 4ms/step - loss: 0.7466
Epoch 6/75
4/4 [==============================] - 0s 4ms/step - loss: 0.7408
Epoch 7/75
4/4 [==============================] - 0s 3ms/step - loss: 0.7327
Epoch 8/75
4/4 [==============================] - 0s 3ms/step - loss: 0.7316
Epoch 9/75
4/4 [==============================] - 0s 4ms/step - loss: 0.7255
Epoch 10/75
4/4 [==============================] - 0s 4ms/step - loss: 0.7221
Epoch 11/75
4/4 [==============================] - 0s 4ms/step - loss: 0.7233
Epoch 12/75
4/4 [==============================] - 0s 3ms/step - loss: 0.7223
Epoch 13/75
4/4 [==============================] - 0s 4ms/step - loss: 0.